package com.facepp.demo;

public class Config {
	public static final String APP_KEY="43d7eac4eff8fe62d22b139d6f02828e";
	public static final String APP_SECRET="14bIP7lF0Y-Bgtw4DzLQhw1vKSe2U7bA";
	public static final String FACESET_NAME="faceset_star"; 
	public static final String FACESET_DETECT="faceset_detect"; 
	public static final String GROUP_NAME="group_star"; 
	public static final String DEFAULT_FACE_ID="3e500e91005e5754338d39a680253add";
	
	public static final String GET_URL="http://tu.baidu.com/i?tn=wisejson&ie=UTF-8&pn=0&rn=50&face=0&lm=7&z=2&word=";
	public static final String PIC_URL="http://i.eimg.com.tw/d/artist/32/2032.300.jpg?ver=86";
	
	public static final String TAG="FACEPP";
	public static final String[] FACES_DELETED=new String[]{
		"e65a7b0d8822f3b2eaeeb05f21713e99",
		"1934d5ca7410ae29cd6261d9944a27fe",
		"31e956385b7feac069bed98eccc49643"
		
	};
	public static final String[] STARS=new String[]{
		"李易峰",
		"成龙",
		"鹿晗",
		"陈冠希",
		"吴亦凡",
		"黄晓明",
		"刘德华",
		"邓超",
		"钟汉良",
		"张杰",
		"陈坤",
		"刘恺威",
		"周杰伦",
		"李敏镐",
		"张翰",
		"魏晨",
		"谢霆锋",
		"彭于晏",
		"文章",
		"李小龙",
		"Rain",
		"吴彦祖",
		"林志颖",
		"罗志祥",
		"王力宏",
		"吴奇隆",
		"古天乐",
		"柯震东",
		"胡歌",
		"张学友",
		"吴尊",
		"尼坤",
		"冯绍峰",
		"霍建华",
		"韩庚",
		"崔始源",
		"吴秀波",
		"贾乃亮",
		"佟大为",
		"宋承宪",
		"赵又廷",
		"苏有朋",
		"乔任梁",
		"林更新",
		"潘玮柏",
		"言承旭",
		"明道",
		"周渝民",
		"阮经天",
		"萧敬腾",
		"范冰冰",
		"Angelababy",
		"杨幂",
		"唐嫣",
		"张馨予",
		"张柏芝",
		"柳岩",
		"刘亦菲",
		"林志玲",
		"张靓颖",
		"高圆圆",
		"刘诗诗",
		"李冰冰",
		"赵丽颖",
		"汤唯",
		"赵薇",
		"舒淇",
		"赵奕欢",
		"李小璐",
		"佟丽娅",
		"林心如",
		"章子怡",
		"李小璐",
		"陈乔恩",
		"黄圣依",
		"蔡依林",
		"霍思燕",
		"谢娜",
		"王丽坤",
		"王菲",
		"李宇春",
		"王珞丹",
		"姚笛",
		"宋茜",
		"马苏",
		"周迅",
		"何洁",
		"郭采洁",
		"朱茵",
		"张雨绮",
		"徐静蕾",
		"桂纶镁",
		"张歆艺",
		"董洁",
		"莫文蔚",
		"袁姗姗",
		"姚晨",
		"陈意涵",
		"张嘉倪",
		"徐璐"
	};
}
